{
 "title": "Thumbor",
 "description": "Simple thumbor metrics using prometheus",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Request",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(thumbor_response_count_total[$__rate_interval]))"
    }
   ]
  },
  {
   "title": "Result Storage Hit",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(thumbor_result__storage_hit_total[$__rate_interval]))"
    }
   ]
  },
  {
   "title": "Result Storage Miss",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(thumbor_result__storage_miss_total[$__rate_interval]))"
    }
   ]
  },
  {
   "title": "Storage Hit",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(thumbor_storage_hit_total[$__rate_interval]))"
    }
   ]
  },
  {
   "title": "Storage Miss",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(thumbor_storage_miss_total[$__rate_interval]))"
    }
   ]
  },
  {
   "title": "Response Time",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(rate(thumbor_response_time_sum{statuscode_extension=\"response.time\"}[$__rate_interval]))"
    }
   ]
  },
  {
   "title": "Thumbor Response Time",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum by (statuscode_extension) (rate(thumbor_response_time_sum[$__rate_interval]))",
     "legendFormat": "{{ statuscode_extension }}"
    }
   ]
  },
  {
   "title": "Processed File Hourly",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (extension) (increase(thumbor_response_bytes_total[$__interval]))",
     "legendFormat": "{{ extension }}"
    }
   ]
  },
  {
   "title": "File Type Hourly",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (extension) (increase(thumbor_response_format_total[$__interval]))",
     "legendFormat": "{{ extension }}"
    }
   ]
  }
 ]
}